server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: usuarios
          uri: http://localhost:8082
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=0
  web:
    resources:
      add-mappings: false  # Desactiva recursos estáticos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost