name: Build and Deploy Eureka Servicio

on:
  push:
    paths:
      - 'microservicios/microservice-eureka/**'
    branches:
      - main  # Cambia esto si tu rama principal se llama diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Give execution permission to mvnw
      run: chmod +x microservicios/microservice-eureka/mvnw

    - name: Build the Spring Boot app
      run: |
        cd microservicios/microservice-eureka
        ./mvnw clean install

    - name: Build Docker image
      run: |
        cd microservicios/microservice-eureka
        docker build -t formidata/microservice-eureka:v1.0.2 .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push formidata/microservice-eureka:v1.0.2